# Generated by Django 2.2.2 on 2019-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='photo',
        ),
        migrations.AddField(
            model_name='modules',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='iot/static/'),
        ),
    ]
