# Generated by Django 2.2.2 on 2019-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20190614_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='modules'),
        ),
    ]
