# Generated by Django 2.2.2 on 2019-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20190615_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='modules',
            name='photos',
            field=models.ImageField(blank=True, upload_to='modules'),
        ),
    ]
