# Generated by Django 2.2.2 on 2019-06-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20190616_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photos', models.ImageField(blank=True, default='modules/missing.png', upload_to='modules')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=20)),
                ('topic_publish', models.CharField(blank=True, max_length=50)),
                ('topic_subscribe', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='modules',
            name='photos',
            field=models.ImageField(blank=True, default='modules/missing.png', upload_to='modules'),
        ),
        migrations.AddField(
            model_name='boards',
            name='processor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processor', to='iot.Modules'),
        ),
        migrations.AddField(
            model_name='boards',
            name='sensor1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor1', to='iot.Modules'),
        ),
        migrations.AddField(
            model_name='boards',
            name='sensor2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor2', to='iot.Modules'),
        ),
        migrations.AddField(
            model_name='boards',
            name='sensor3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor3', to='iot.Modules'),
        ),
        migrations.AddField(
            model_name='boards',
            name='sensor4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor4', to='iot.Modules'),
        ),
    ]
