# Generated by Django 2.2.2 on 2019-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20190619_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
