# Generated by Django 2.2.2 on 2019-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20190619_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='location',
            field=models.CharField(choices=[('LR', 'Leavingroom'), ('KR', 'Kitchen')], default='LR', max_length=2),
        ),
    ]
