# Generated by Django 2.2.2 on 2019-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_auto_20190619_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='location',
            field=models.CharField(choices=[('LR', 'Leavingroom'), ('KN', 'Kitchen'), ('KR', 'Corridor'), ('BR', 'bedroom'), ('RR', 'restroom')], default='LR', max_length=2),
        ),
    ]
