# Generated by Django 2.2.2 on 2019-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_auto_20190619_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='boards',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='location',
            field=models.CharField(choices=[('LR', 'Leavingroom'), ('KN', 'Kitchen'), ('KR', 'Corridor'), ('BR', 'Bedroom'), ('RR', 'Restroom')], default='LR', max_length=2),
        ),
    ]
