# Generated by Django 2.2.2 on 2019-07-23 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_auto_20190624_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mqttypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('S', 'subscribe'), ('P', 'publish')], default='S', max_length=2)),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.TextField()),
                ('topic', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='iot.Mqttypes')),
            ],
        ),
    ]
