# Generated by Django 2.1.7 on 2020-02-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_mqtt_mqttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='processor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processor', to='iot.Modules'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='sensor1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor1', to='iot.Modules'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='sensor2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor2', to='iot.Modules'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='sensor3',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor3', to='iot.Modules'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='sensor4',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor4', to='iot.Modules'),
        ),
    ]
