# Generated by Django 2.1.7 on 2019-03-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt',
            name='created_date',
        ),
    ]
