# Generated by Django 2.1.7 on 2019-03-08 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0002_remove_mqtt_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
