# Generated by Django 2.1.7 on 2020-02-07 16:36

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0005_gaz'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gaz',
            managers=[
                ('price_liter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gaz',
            name='millage',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='gaz',
            name='station_type',
            field=models.CharField(blank=True, choices=[('BRSM', 'BRSM'), ('KLO', 'KLO'), ('LPG', 'LPG'), ('WOG', 'WOG')], default='BRSM', max_length=6),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='fuel_type',
            field=models.CharField(choices=[('GAZ_95', 'Gaz_95'), ('GAZ_98', 'Gaz_98'), ('LPG', 'LPG')], default='LPG', max_length=6),
        ),
    ]
