# Generated by Django 2.1.7 on 2020-02-17 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0006_auto_20200207_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='gazoline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(choices=[('B', 'B'), ('LPG', 'LPG')], default='LPG', max_length=7)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_liter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_after_disc', models.DecimalField(decimal_places=2, max_digits=7)),
                ('millage', models.PositiveIntegerField(default=120000)),
                ('station', models.CharField(blank=True, choices=[('BRSM', 'BRSM'), ('KLO', 'KLO'), ('LPG', 'LPG'), ('WOG', 'WOG'), ('Other', 'Other')], default='BRSM', max_length=6)),
            ],
            options={
                'ordering': ['-created_date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='gaz',
        ),
    ]
