# Generated by Django 2.1.7 on 2020-04-07 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0007_auto_20200217_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='orbi_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=0)),
                ('time', models.DecimalField(decimal_places=2, max_digits=7)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='orbitrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
