# Generated by Django 2.1.7 on 2020-12-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0010_gaz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gaz',
        ),
    ]
