# Generated by Django 2.1.7 on 2020-12-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0011_delete_gaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazoline',
            name='millage',
            field=models.PositiveIntegerField(default=240000),
        ),
    ]
