# Generated by Django 2.1.7 on 2020-12-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0012_auto_20201225_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='measured_time',
            field=models.CharField(max_length=100),
        ),
    ]
