# Generated by Django 2.1.7 on 2020-12-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0013_auto_20201225_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='power',
            field=models.DecimalField(decimal_places=3, default=200, max_digits=10),
            preserve_default=False,
        ),
    ]
