# Generated by Django 2.1.7 on 2021-03-15 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0014_electricity_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='electrometr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('measured_time', models.CharField(max_length=100)),
                ('current', models.DecimalField(decimal_places=3, max_digits=10)),
                ('energy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frequency', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=3, max_digits=10)),
                ('power', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
