# Generated by Django 2.2.19 on 2021-04-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0015_electrometr'),
    ]

    operations = [
        migrations.CreateModel(
            name='electrozones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('energy_day', models.DecimalField(decimal_places=3, max_digits=10)),
                ('energy_night', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
