# Generated by Django 2.2.19 on 2021-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome_1', '0016_electrozones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrozones',
            name='created_date',
            field=models.DateField(unique=True),
        ),
    ]
